Download JARs in run_codenarc.py script
Ableton/groovylint pull request #188
Opened 2021-03-31 11:26 UTC by nre-ableton

Now that we no longer rely on `requests` to download JAR files, we don't need a
separate script to do it either.

2021-04-01 15:18 UTC, rco-ableton reviewed
Just one question.

2021-04-01 15:18 UTC, rco-ableton commented on run_codenarc.py
> -    parsed_args.codenarc_options = [
Did you mean to move this?

2021-04-01 15:29 UTC, ala-ableton commented
@nre-ableton As you may have guessed, I'm interested in reviewing this PR 😄

2021-04-01 15:49 UTC, nre-ableton commented on run_codenarc.py
> -    parsed_args.codenarc_options = [
Well, kind of. I actually moved the bit below this to set the logging level, but the diff renders it like I moved this chunk of code instead. The idea is that we need to set the logging level earlier, otherwise we don't see what's going on when downloading the jars.

2021-04-05 08:55 UTC, rco-ableton commented on run_codenarc.py
> -    parsed_args.codenarc_options = [
A-ha, okay. Thanks for the explanation!

2021-04-05 08:55 UTC, rco-ableton approved these changes
LGTM 👍

2021-04-06 06:22 UTC, nre-ableton commented
@ablbot rebase

2021-04-06 14:11 UTC, ala-ableton requested changes
This is an API breaking change, please bump the version. Thanks!

2021-04-06 14:11 UTC, ala-ableton commented on run_codenarc.py
> +        _fetch_jars(parsed_args)
These lines don't belong in `parse_args`. Please move them outside of that function. It will also avoid moving  `parsed_args.codenarc_options` (which Rhys found weird).

2021-04-06 14:48 UTC, nre-ableton commented on run_codenarc.py
> +        _fetch_jars(parsed_args)
Fixed in 26d6f68.

2021-04-06 14:57 UTC, ala-ableton reviewed
Please rebase/squash and revert the unnecessary changes in `parse_args`. Then I'll do another review, thanks!

2021-04-06 15:12 UTC, nre-ableton commented
> Please rebase/squash and revert the unnecessary changes in `parse_args`. Then I'll do another review, thanks!

Done. I had to make a few cleanups to satisfy pylint, though.

2021-04-06 15:15 UTC, ala-ableton commented on run_codenarc.py
> +    args = arg_parser.parse_args()
Why?

2021-04-06 15:17 UTC, nre-ableton commented on run_codenarc.py
> +    args = arg_parser.parse_args()
Because I need to use `parsed_args` in the main application loop (ie, outside of any function), or else pylint complains about shadowing. I can't call it `args` there or else a bunch of other functions will shadow _that_.

2021-04-06 15:23 UTC, ala-ableton commented on run_codenarc.py
> +    args = arg_parser.parse_args()
I see. Please reword https://github.com/Ableton/groovylint/pull/188/commits/8ed85823368e8c590c02aadda14d0c9d7031d167 to "Rename local variable to avoid shadowing in the next commit".

2021-04-07 09:18 UTC, nre-ableton commented
@ala-ableton I decided to drop my cleanup commit _Cleanup: don't pass sys.argv to parse_args_ since it was more trouble than it was worth (namely, it would require reworking a bunch of tests). Please have another look!

2021-04-07 12:43 UTC, ala-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
This doesn't simply download the JAR files, it also runs CodeNarc, but on no input. Is this really what we want?

2021-04-07 12:50 UTC, nre-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
I noticed this as well, but IMHO it's not a huge problem when building the container. The bigger question is whether `--download` should return after downloading JARs, or whether it should download JARs first and then run. I think the latter is more convenient.

2021-04-14 08:03 UTC, nre-ableton commented
Re-ping @ala-ableton

2021-04-19 11:07 UTC, ala-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
Before, we had 2 scripts that would each perform one task (let's call the tasks A and B). This meant that we could do only A, or only B, or do both tasks by calling both scripts. In the current state of the PR, we can't do only A, and this makes Groovylint less flexible.
As you proposed, we could have a single script that is capable of doing only A, or only B, and in order to do both tasks we would have to call that script twice. But this makes me wonder, why not keep two scripts? I don't see in this PR's description or in the commit messages why having a single script is better than two.

2021-04-19 12:48 UTC, nre-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
@ala-ableton Here are the benefits (as I see them) for having a single script:

1. It is easier for users to understand. Instead of having to fetch JARs separately, there is just one script that you can go to, period.
2. The ultimate goal of this work is to be able to use groovylint outside of a Docker container from a Jenkins pipeline library. For that to happen, we need to use the `libraryResource` to have Jenkins return the script as a `String`, and then use `writeFile` before we can call `sh` on the resulting script. Having to do this once is pretty ugly, but twice is of course more awkward.

Here's another suggestion: maybe we just get rid of the `--download` option altogether, and change the script so that it downloads JARs if they are not found in the resources directory. That way, we don't have tasks A and B, but just task A, and B is considered a part of that task.

2021-04-20 16:19 UTC, ala-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
> Here's another suggestion: maybe we just get rid of the `--download` option altogether, and change the script so that it downloads JARs if they are not found in the resources directory. That way, we don't have tasks A and B, but just task A, and B is considered a part of that task.

That sounds like a good option. I'll let you rework the PR to do this.

2021-04-20 16:54 UTC, nre-ableton commented on Dockerfile
> +RUN python3.8 run_codenarc.py --download --resources /opt/resources \
@ala-ableton Great, please take another look when you have a moment!

2021-04-20 17:50 UTC, ala-ableton reviewed
It seems that the commit that bumps the version got removed when rebasing.

2021-04-20 18:27 UTC, nre-ableton commented
@ala-ableton Yes, indeed. :sweat_smile: Fixed!

2021-04-23 10:41 UTC, ala-ableton approved these changes

2021-04-23 13:17 UTC, nre-ableton commented
@ablbot rebase

2021-04-23 14:19 UTC, merged