Store JAR versions in a Maven pom.xml file
Ableton/groovylint pull request #189
Opened 2021-04-01 13:40 UTC by nre-ableton

Yes, Maven. 😅 However, storing the JAR versions here offers two big advantages:

1. It allows the `pom.xml` to act as the canonical source for the default versions of all JAR files.
2. It enables us to use dependabot to bump our library versions.

2021-04-01 14:59 UTC, nre-ableton commented
@ablbot autosquash

2021-04-27 07:42 UTC, ala-ableton commented
@nre-ableton I'm interested in reviewing this PR, thanks!

2021-04-28 16:29 UTC, nre-ableton commented
@ala-ableton As @dgl-ableton is OOO until Tuesday (and is likely finished working today), please feel free to start the review!

2021-05-03 15:17 UTC, ala-ableton requested changes
A few comments on the first 2 commits.

2021-05-03 15:17 UTC, ala-ableton commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
```suggestion
    <version>0.12.0</version>
```

2021-05-03 15:17 UTC, ala-ableton commented on run_codenarc.py
> +GROOVYLINT_HOME = os.path.realpath(os.path.dirname(__file__))
```suggestion
GROOVYLINT_HOME = os.path.dirname(os.path.realpath(__file__))
```

2021-05-04 10:23 UTC, nre-ableton commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Technically, it should technically be `0.13.0-SNAPSHOT` (see https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855), and then set to `0.13.0` when we actually bump the version number. I think that this advice is really more relevant when releasing a JAR or something. What do you think?

2021-05-04 10:23 UTC, nre-ableton commented on run_codenarc.py
> +GROOVYLINT_HOME = os.path.realpath(os.path.dirname(__file__))
@ala-ableton Sure, but why?

2021-05-04 10:44 UTC, ala-ableton commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Settings it to `0.13.0-SNAPSHOT` in this PR is fine, as long as we remember to change it to `0.13.0` when we change the `VERSION` file.

2021-05-04 10:47 UTC, ala-ableton commented on run_codenarc.py
> +GROOVYLINT_HOME = os.path.realpath(os.path.dirname(__file__))
`os.path.dirname('run_codenarc.py')` returns the empty string. In the case of `os.path.realpath`, it's not a big deal, but passing an empty string (instead of `'.'`) to other `os.path`/`Pathlib` functions can result in unexpected behaviors. That's why `os.path.dirname(__file__)` should be avoided.

2021-05-04 10:52 UTC, ala-ableton approved these changes
Once the version changed in `pom.xml` and rebased, LGTM 👍🏻

2021-05-04 11:20 UTC, nre-ableton commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Sure, see 23342d3 and d748486.

2021-05-04 14:36 UTC, ala-ableton commented on README.md
> +   with the version number `0.100.0-SNAPSHOT` as the version number.
This is getting quite convoluted for a project that actually doesn't use/depend on Maven. I think just keeping `pom.xml` and `VERSION` in sync would be enough.

2021-05-04 15:50 UTC, nre-ableton commented on README.md
> +   with the version number `0.100.0-SNAPSHOT` as the version number.
Sure. Fixed in 4ad1d7a, c365080.

2021-05-05 12:31 UTC, ala-ableton commented
@ablbot autosquash

2021-05-05 12:37 UTC, nre-ableton commented
@ala-ableton Are you still ok with this change? You did approve it, but that was before we had some more discussions about verisoning.

2021-05-05 12:48 UTC, ala-ableton approved these changes
Yep, all good!

2021-05-05 12:50 UTC, merged