Make functions to dowload files more robust
Ableton/groovylint pull request #287
Opened 2022-08-29 16:02 UTC by nre-ableton

It seems that we often get various error codes from GitHub when downloading JAR files, or sometimes plaintext files masquerading as zipfiles. This PR adds a retry loop to the download function (with exponential backoff) and adds additional verification to make sure that the JAR files are first and foremost valid zipfiles.

2022-08-29 16:35 UTC, ala-ableton commented
@nre-ableton I'm interested in reviewing this PR, thanks!

2022-08-30 11:10 UTC, rco-ableton approved these changes

2022-08-30 14:46 UTC, ala-ableton requested changes

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
> +    download_attempt = MAX_DOWNLOAD_ATTEMPTS
Please add a docstring to `_download_file_with_retry` for consistency.

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
> +            logging.error("Download failed with code %d", http_error.code)
In bb2a8938cbea4d5316ad7551e0370928656d56b5, please log `url` here, otherwise we don't know what failed to be downloaded.

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
> +            logging.warning("Download failed with code %d", http_error.code)
In 2842fcb503acd172e9c92a588e2945730b468e63, please log `url` here, otherwise we don't know what failed to be downloaded.

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
> +        if not _verify_jar(_download_file_with_retry(url, args.resources)):
Now that it returns a boolean, I think we should rename `_verify_jar` to `_is_valid_jar`

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
> +            if not _verify_jar(output_file_path):
In 6ef11d0244a6be0e7a65c5a6a357a83bb946311f, `_download_file_with_retry` should probably be renamed to `_download_jar_with_retry`, since it's not generic anymore.

2022-08-30 14:46 UTC, ala-ableton commented on run_codenarc.py
>              raise ValueError("Failed to verify JAR file")
In 6ef11d0244a6be0e7a65c5a6a357a83bb946311f, `_download_file_with_retry` doesn't return a boolean, it returns a path.

2022-08-30 15:18 UTC, nre-ableton commented on run_codenarc.py
>              raise ValueError("Failed to verify JAR file")
Fixed in 2d5dac4. Again, I'll clean up history during rebase.

2022-08-30 15:18 UTC, nre-ableton commented on run_codenarc.py
> +            logging.error("Download failed with code %d", http_error.code)
Well, since the downloads are done in serial, we know what is being downloaded because of the earlier logging message. Admittedly, that's a `debug` level message, but since I usually run the script with `-v`, I probably didn't consider this. Fixed in 03e2136.

2022-08-30 15:18 UTC, nre-ableton commented on run_codenarc.py
> +    download_attempt = MAX_DOWNLOAD_ATTEMPTS
Fixed in b8a841b.

2022-08-30 15:19 UTC, nre-ableton commented
@ala-ableton Let me know when I should squash/rewrite.

2022-08-30 15:21 UTC, ala-ableton commented on run_codenarc.py
> +            if not _verify_jar(output_file_path):
Please don't forget to rename the tests.

2022-08-30 15:21 UTC, ala-ableton reviewed
Feel free to rebase/squash whenever you want.

2022-08-30 20:23 UTC, ala-ableton requested changes

2022-08-30 20:23 UTC, ala-ableton commented on run_codenarc.py
> +        if 500 <= http_error.code < 600:
In 499e60256c5af9c6c2b6e49bf234f01a69589935, a test was added. Why not in c324e403bcd7cdb992c5aa5616a9710c862a9d41?

2022-08-30 20:23 UTC, ala-ableton commented on run_codenarc.py
> -
In f6fcca47bd48ed20614aa35495900f8ad7c76ebc, please keep the empty line.

2022-08-30 20:23 UTC, ala-ableton commented on tests/test_run_codenarc.py
> +def test_download_file_with_retry_fail_verification(sleep_mock):
In 3bfd9cc4f86f64e4f06e29825f35759aa9ee9bc0, please rename the tests and reword the docstrings.

2022-08-31 08:50 UTC, nre-ableton commented
@ablbot runci

2022-08-31 09:02 UTC, nre-ableton commented on run_codenarc.py
> -
Whoops, must have been a rebase error. Fixed in 5e546b8.

2022-08-31 09:07 UTC, nre-ableton commented on run_codenarc.py
> +        if 500 <= http_error.code < 600:
Fixed in 947191e.

2022-08-31 09:07 UTC, nre-ableton commented on tests/test_run_codenarc.py
> +def test_download_file_with_retry_fail_verification(sleep_mock):
Fixed in 77cb4bd.

2022-09-01 14:30 UTC, ala-ableton reviewed
Please rebase/squash after addressing my last comments and I'll have a final look, thanks!

2022-09-01 14:30 UTC, ala-ableton commented on run_codenarc.py
> +    """Verify that a file is a valid JAR file."""
In 71277ff909e7846af8bc6ed6a49c977ea23162db, please consider rewording the docstring.

2022-09-01 14:30 UTC, ala-ableton commented on tests/test_run_codenarc.py
> +                _verify_jar_mock.return_value = False
```suggestion
        with patch("run_codenarc._is_valid_jar") as _is_valid_jar_mock:
            _is_valid_jar_mock.return_value = False
            with patch("os.unlink"):
```

2022-09-01 14:30 UTC, ala-ableton commented on tests/test_run_codenarc.py
> +            _verify_jar_mock.return_value = True
```suggestion
        with patch("run_codenarc._is_valid_jar") as _is_valid_jar_mock:
            _is_valid_jar_mock.return_value = True
```

2022-09-05 13:39 UTC, ala-ableton approved these changes
One last comment, then LGTM 👍🏻

2022-09-05 13:39 UTC, ala-ableton commented on run_codenarc.py
> -    with zipfile.ZipFile(file_path, "r") as jar_file:
In 7d77b2677c27ad44ae3fdd3fd39970306dfeba81's commit message: _verify_jar -> _is_valid_jar

2022-09-05 13:54 UTC, nre-ableton commented on run_codenarc.py
> -    with zipfile.ZipFile(file_path, "r") as jar_file:
Fixed in 864033e. I didn't notice you approved, so you can disregard the review request. I'll just go ahead and merge.

2022-09-05 14:01 UTC, merged