Update Python to v3.10.6
Ableton/groovylint pull request #290
Opened 2022-09-12 17:20 UTC by rco-ableton

2022-09-12 20:24 UTC, mst-ableton approved these changes

2022-09-13 09:20 UTC, ala-ableton requested changes
AFAICT, `.python-version` is "ignored" by this repository. It was not touched in https://github.com/Ableton/groovylint/pull/246. So changing the Python version in `.python-version` only doesn't do much.

2022-09-13 11:09 UTC, rco-ableton commented
@ala-ableton good catch! I guess the most we can do here is to read `.python-version` from the `Jenkinsfile`—the `Dockerfile` references only `python3.10`, so shouldn't be affected by patch bumps. See https://github.com/Ableton/groovylint/pull/290/commits/92293524183c6455efecead915c158f0ef3e6557. If that makes sense to you, I'll reverse the two commits on this branch before merging.

2022-09-13 14:27 UTC, ala-ableton approved these changes
LGTM with the commit swapped.

2022-09-13 14:36 UTC, merged