Add type hinting to Python code
Ableton/groovylint pull request #452
Opened 2024-05-28 11:54 UTC by nre-ableton

- Add type hinting to Python code
- Enable ruff's type hinting checks

2024-05-28 13:45 UTC, anz-ableton requested changes

2024-05-28 13:45 UTC, anz-ableton commented on pyproject.toml
> +ignore = ["ANN101", "ANN401"]
If I remove this ignore list and run `ruff check` then only `ANN101` is reported:

    run_codenarc.py:35:18: ANN101 Missing type annotation for `self` in method`

```suggestion
ignore = ["ANN101"]
```

Alternatively, we can use `Self` from `typing` because Python 3.12 implements [PEP 673](https://peps.python.org/pep-0673/):

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 34d9bce..309831b 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -9,7 +9,6 @@ line-length = 90
 target-version = "py312"
 
 [tool.ruff.lint]
-ignore = ["ANN101", "ANN401"]
 select = ["ANN", "C90", "D", "E", "F", "I", "PL", "W"]
 
 [tool.ruff.lint.isort]
diff --git a/run_codenarc.py b/run_codenarc.py
index 9694e8b..9877cc7 100755
--- a/run_codenarc.py
+++ b/run_codenarc.py
@@ -18,7 +18,7 @@ import tempfile
 import time
 import zipfile
 
-from typing import Dict, List, Optional
+from typing import Dict, List, Optional, Self
 from urllib.error import HTTPError
 from urllib.request import urlopen
 from xml.etree import ElementTree
@@ -32,7 +32,7 @@ MAX_DOWNLOAD_ATTEMPTS = 5
 class CodeNarcViolationsException(Exception):
     """Raised if CodeNarc violations were found."""
 
-    def __init__(self, num_violations: int) -> None:
+    def __init__(self: Self, num_violations: int) -> None:
         """Create a new instance of the CodeNarcViolationsException class."""
         super().__init__()
         self.num_violations = num_violations
```

2024-05-29 06:35 UTC, nre-ableton commented on pyproject.toml
> +ignore = ["ANN101", "ANN401"]
Fixed in 7ff1085.

2024-05-29 07:51 UTC, anz-ableton approved these changes
LGTM.

2024-05-29 07:59 UTC, nre-ableton commented
@ablbot autosquash

2024-05-29 08:01 UTC, merged